---
apiVersion: v1
kind: Service
metadata:
  name: gocron
  labels:
    app: gocron
spec:
  ports:
  - port: 5920
    name: gocron
  type: NodePort
  selector:
    app: gocron
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    name: gocron
  name: gocron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gocron
  template:
    metadata:
      labels:
        app: gocron
    spec:
      containers:
      - name: gocron
        image: ouqg/gocron
        ports:
        - containerPort: 5920